language: node_js
node_js: node
cache: npm
notifications:
  slack: cse112-sp19-team3:vGyQXkfhyYbp46A5tXNzwUUb
before_install:
    - npm install -g npm@latest
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
install:
    - npm install
script:
    - rm -rf ./docs/*.html
    - npm run htmlhint
    - npm run csslint
    - npm run eslint
    - commitlint-travis
    - npm run test
    - npm run browserstack
    - npm generate-docs

after_script:
    - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

addons:
  browserstack:
    username: rixlai1
    access_key:
      secure: qNTBFrxqcUA5x032UmKW7fnr7IzeVzDrRFUTypFgWnx4S9IKFmsES0L1Y9mBD2IjNSrvkIDjKGUBKIP8HfCwgS7wDqdqPjmRIawIelMvVmYMZtBl5w4jIzYKdgsUvK2HzAK5UNSnR4FAN3sOUofEmyinSnK0bo8a4HbMw7WAjp5IZ9n/HW/w/BZF5yrAXEWYm8wLLY9uATg9zv6PIg3HJRMJJp9jlu70Klcbi+bkttF+Kp96LOUAeHCuZ0pfPl+saogAVkJpm1mSd4dQxjYu8DKL6jq6JK8mnKw6QRUXXMGZnsBex49Uuqx/rlpZNb+luFiFnPS0VxmH5XFDSrIAzM7YOVABo+1MnrziO3y6TBi2VxhO8bTK6q+22a2ZwydwsLNO5hyYbnMZlfAMQuQF8+Bv6e0/5/MMmJamlgbjaoPy0xmFRHwrRBxcMfU72wib5FU53St7NBYBNYrqd49sV/x/CYXt6lDs/SjDfQifGxiGSsMb99ttH6ecAUDXUlTRxcqpS6aapW/8+e6Lk+M8inQZ94mYGTvS+JnN4ZTEFrwskzs70ouF/udijKWIFpeGVC0QuCK+QN8Tqi6f6O7kYPlaItbmXE5XQA6G9XlOvSiXexCR1Vd0xEj45U+50665MXwZQFiXflNxIZ4L5I8tMjttQxzD/yThV58bguRbRsY=
env:
  global:
  - CC_TEST_REPORTER_ID=e44311501b10676704e6161fe012dd1cb0c52584c6c1e9cb96dfe8978ddc3dec
  - secure: pu0fPGd5+EmjSu0R26KriIBPmLmmMFswxLtvkeuk46Xl66Pc/h4TE4PUQHK+n5eI+IFhHAfmNHvRoq3txT+o+OAmK3VcXyzSRn1/8UaX6qbiO84/dgHpEw5yZugNnQZp97uKedKZG2w5WFwL3ZitqUIRvdi8lOD0Z24EWYxcbJaiUHn8r7ZzHR4NtNHzbAdLh+SpRKOJfslbwOvNXmzeGNr02zhYLpDdXCaRcBF5kr4t2RBG+DuLlVDE3HcQ9qWAHkmf7yFAOXJ3LFveZsKUv61Q6plSABQyPeXBjn8V+N05WZj5fYgXplGMXCIhFJ9+m5hkmWOwkOydbYUk1/bxV5ACJTroVq9qGflrE1xpdC/cabUc8t0W9uLevbAZen9+244wSJGJlHvEQDRCj3P02SINNbCv9Af1vrLCXpXoV7/eupOuMtTEorpR3pU2T5BHaE2E5UKurKwTSL57pDhnThv1RzdkaiO8IQolFHd2hk6JWGHxY+RJjY0ua22+xskKpFf0+1BUdgm5RiHiLaY7+d3fz8toMaCplBasOg4R0LfSFlHHi8TZtAmOSPR+cuBOt62efYa0WxQzkucXbGWoMlYN1ySX3Q/S057TjOUn9JLRkluhRKEwyrdf/VYsr+oTNDyBqEljBNML5NBKbmAGhdGSdcFImePpMN89CzgbUsU=
